image:
  repository: 140147588849.dkr.ecr.us-west-2.amazonaws.com/goit-app-repo
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

deployment:
  replicas: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  readiness:
    enabled: true
    path: /
    initialDelaySeconds: 30
    periodSeconds: 10
  liveness:
    enabled: true
    path: /
    initialDelaySeconds: 60
    periodSeconds: 30

env:
  SECRET_KEY: "django-insecure-p_%rehih6bqa6*1td@b^j6hw8&@i8xw850o2z=7&j*ssi+b)&f"
  DEBUG: "True"
  ALLOWED_HOSTS: "*"
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "mydb"
  DB_USER: "myuser"
  DB_PASSWORD: "mypassword"
  DB_HOST: "db"
  DB_PORT: "5432"
