apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-django
  labels:
    app.kubernetes.io/name: django
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-django
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
